import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

import { GROUND_TILES, GROUND_TILE_M, GROUND_TILE_PX, GROUND_ZONES } from '../src/data/groundTiles.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const TEX = (rel) => path.join(ROOT, 'vendor', 'textures', rel);

// STEP ONE OF THE COURSE — THE GROUND.
//
// src/data/groundTiles.js is generated by tools/course/turf.py, and the terrain
// shader reads its numbers as compile-time constants: each zone's colour is
// `tile * (target / tile mean)`, so a recorded mean that no longer matches the
// PNG shifts every fairway, green and bunker in the game by the ratio of the
// error and nothing anywhere says so.
//
// Python is not available in the suite, so this does not regenerate. It reads
// the PNGs that ship and checks the record against them. That is the stronger
// check anyway: it fails if EITHER side is edited alone.

const srgbToLinear = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);

async function raw(file) {
  const { data, info } = await sharp(TEX(file)).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  return { data, w: info.width, h: info.height, ch: info.channels };
}

test('every ground tile has both of its maps on disk at the recorded size', async () => {
  for (const [name, t] of Object.entries(GROUND_TILES)) {
    for (const f of [t.albedo, t.normal]) {
      assert.ok(fs.existsSync(TEX(f)), `${f} is missing — the ground would fall back to the canvas procedural`);
      const meta = await sharp(TEX(f)).metadata();
      assert.equal(meta.width, GROUND_TILE_PX, `${f} is ${meta.width} px, not ${GROUND_TILE_PX}`);
      assert.equal(meta.height, GROUND_TILE_PX);
      assert.equal(meta.channels, 4,
        `${f} must be RGBA: roughness rides in the albedo's alpha and occlusion in the normal's blue`);
    }
    assert.ok(name.length > 0);
  }
});

test('the recorded mean linear colour is the mean of the albedo that ships', async () => {
  for (const [name, t] of Object.entries(GROUND_TILES)) {
    const { data, w, h, ch } = await raw(t.albedo);
    const sum = [0, 0, 0];
    const n = w * h;
    for (let i = 0; i < n; i += 1) {
      for (let c = 0; c < 3; c += 1) sum[c] += srgbToLinear(data[i * ch + c] / 255);
    }
    const mean = sum.map((s) => s / n);
    for (let c = 0; c < 3; c += 1) {
      assert.ok(Math.abs(mean[c] - t.meanLinear[c]) < 0.004,
        `${name} channel ${c}: the map means ${mean[c].toFixed(5)}, the record says `
        + `${t.meanLinear[c].toFixed(5)} — regenerate with: python tools/course/turf.py`);
    }
  }
});

test('roughness is a MAP, not a constant, and it lands near the authored centre', async () => {
  // The whole reason the ground had no wet-versus-dry look is that roughness was
  // a per-zone scalar. If the alpha channel is flat, that is back.
  for (const [name, t] of Object.entries(GROUND_TILES)) {
    const { data, w, h, ch } = await raw(t.albedo);
    let lo = 255; let hi = 0; let sum = 0;
    const n = w * h;
    for (let i = 0; i < n; i += 1) {
      const a = data[i * ch + 3];
      lo = Math.min(lo, a); hi = Math.max(hi, a); sum += a;
    }
    assert.ok(hi - lo >= 8, `${name} roughness spans only ${hi - lo}/255 — that is a constant with extra steps`);
    const mean = sum / n / 255;
    assert.ok(Math.abs(mean - t.roughness) < 0.06,
      `${name} roughness averages ${mean.toFixed(3)}, authored ${t.roughness}`);
  }
});

test('the normal maps carry real slope, and their xy stays inside the unit circle', async () => {
  // z is reconstructed in the shader as sqrt(1 - x*x - y*y). An xy pair outside
  // the unit circle makes that a square root of a negative number, and the
  // clamp that saves it from NaN produces a normal pointing along the surface.
  for (const [name, t] of Object.entries(GROUND_TILES)) {
    const { data, w, h, ch } = await raw(t.normal);
    const n = w * h;
    let worst = 0; let sumSq = 0; let flat = 0;
    for (let i = 0; i < n; i += 1) {
      const x = (data[i * ch] / 255) * 2 - 1;
      const y = (data[i * ch + 1] / 255) * 2 - 1;
      const r2 = x * x + y * y;
      worst = Math.max(worst, r2);
      sumSq += r2;
      if (r2 < 1e-4) flat += 1;
    }
    assert.ok(worst < 0.98, `${name}: a normal xy of ${Math.sqrt(worst).toFixed(3)} leaves no z to reconstruct`);
    const rms = Math.sqrt(sumSq / n);
    assert.ok(rms > 0.01, `${name}: normal xy rms ${rms.toFixed(4)} — the map is flat, which is the fault being fixed`);
    assert.ok(flat / n < 0.5, `${name}: ${Math.round((flat / n) * 100)}% of the map is dead flat`);
  }
});

test('occlusion is present in the normal map blue and actually occludes', async () => {
  for (const [name, t] of Object.entries(GROUND_TILES)) {
    const { data, w, h, ch } = await raw(t.normal);
    const n = w * h;
    let lo = 255; let sum = 0;
    for (let i = 0; i < n; i += 1) {
      const b = data[i * ch + 2];
      lo = Math.min(lo, b); sum += b;
    }
    assert.ok(lo < 250, `${name}: occlusion never drops below ${lo}/255 — nothing is in shadow`);
    const mean = sum / n / 255;
    assert.ok(mean > 0.4 && mean < 0.999, `${name}: occlusion mean ${mean.toFixed(3)} is not a plausible cavity map`);
  }
});

test('every zone the shader names resolves to a surface that exists', () => {
  const surfaces = new Set(Object.keys(GROUND_TILES));
  for (const [zone, z] of Object.entries(GROUND_ZONES)) {
    assert.ok(surfaces.has(z.surface), `zone ${zone} points at ${z.surface}, which is not a tile`);
    assert.equal(z.mul.length, 3);
    for (const m of z.mul) {
      assert.ok(Number.isFinite(m) && m > 0 && m < 8,
        `zone ${zone} multiplier ${m} is not a plausible ratio — check the target mean in turf.py`);
    }
  }
  // The turf zones must keep the tuned parkland colour they had before the
  // tiles landed: multiplier times tile mean is the tuned target, and drifting
  // that silently re-grades the whole course.
  const fair = GROUND_ZONES.fair;
  const tile = GROUND_TILES[fair.surface].meanLinear;
  const landed = fair.mul.map((m, i) => m * tile[i]);
  const tuned = [0.1163, 0.2519, 0.0620];
  for (let i = 0; i < 3; i += 1) {
    assert.ok(Math.abs(landed[i] - tuned[i]) < 0.002,
      `the fairway now averages ${landed[i].toFixed(4)} where it was tuned to ${tuned[i]}`);
  }
});

test('the terrain shader binds the tiles, and stays under WebGL\'s 16 texture units', () => {
  const src = fs.readFileSync(path.join(ROOT, 'src/render3d/courseScene.js'), 'utf8');
  const block = src.slice(src.indexOf('terrainMat.onBeforeCompile'), src.indexOf('const terrain = new THREE.Mesh'));
  const samplers = new Set();
  for (const m of block.matchAll(/shader\.uniforms\.(\w+)\s*=\s*\{\s*value:\s*(tex|zone|aux|plan|surface)\w*/g)) {
    samplers.add(m[1]);
  }
  // + map and normalMap, which the material owns rather than the uniform block
  const total = samplers.size + 2;
  assert.ok(total <= 14,
    `${total} ground/data samplers plus two RectAreaLight LTC lookups must stay under 16; found ${[...samplers].join(', ')}`);
  for (const need of ['tRoughA', 'tRoughN', 'tSandA', 'tSandN', 'tHardA', 'tHardN']) {
    assert.ok(samplers.has(need), `the terrain shader no longer binds ${need}`);
  }
  assert.ok(!/FW_STYLIZE\(/.test(block),
    'FW_STYLIZE is back: that macro is what reduced every ground photograph to its luminance');
  assert.ok(GROUND_TILE_M > 0);
});
