// Bounded, aggregated divots and ball marks generated by real play. Counts live
// per turf cell (not one object per mark), so they persist exactly and can feed
// localized terrain wear without creating an unbounded render/physics system.

import { ZONE } from './constants.js';
import { calendarOf } from './time.js';
import { clamp, rngOf } from '../core/utils.js';

export const SURFACE_DAMAGE_CAP = 6;

export function ensureSurfaceDamage(state) {
  if (!state.turf || !state.course) return;
  const n = state.course.w * state.course.h;
  if (!(state.turf.divots instanceof Float32Array) || state.turf.divots.length !== n) {
    const previous = state.turf.divots || [];
    state.turf.divots = new Float32Array(n);
    state.turf.divots.set(Array.from(previous).slice(0, n));
  }
  if (!(state.turf.ballMarks instanceof Float32Array) || state.turf.ballMarks.length !== n) {
    const previous = state.turf.ballMarks || [];
    state.turf.ballMarks = new Float32Array(n);
    state.turf.ballMarks.set(Array.from(previous).slice(0, n));
  }
}

export function seedSurfaceDamage(state) {
  ensureSurfaceDamage(state);
  const { zones } = state.course;
  const t = state.turf;
  for (let i = 0; i < zones.length; i += 1) {
    if ((zones[i] === ZONE.TEE || zones[i] === ZONE.FAIRWAY) && t.wear[i] > 22 && i % 5 === 0) {
      t.divots[i] = 1 + (i % 2);
    }
    if (zones[i] === ZONE.GREEN && t.wear[i] > 12 && i % 4 === 0) {
      t.ballMarks[i] = 1 + (i % 3 === 0 ? 1 : 0);
    }
  }
}

export function surfaceDamageDaily(state) {
  ensureSurfaceDamage(state);
  if (!state.turf) return { divots: 0, ballMarks: 0 };
  const t = state.turf;
  const zones = state.course.zones;
  const day = calendarOf(state.clock.minutes).dayAbs;
  const divotCells = [];
  const markCells = [];

  // Natural recovery is intentionally slow, bounded, and deterministic. A missed
  // day matters, while a week away does not permanently ruin the property.
  for (let i = 0; i < zones.length; i += 1) {
    if ((i + day) % 6 === 0) {
      t.divots[i] = Math.max(0, t.divots[i] - 0.25);
      t.ballMarks[i] = Math.max(0, t.ballMarks[i] - 0.35);
    }
    if (zones[i] === ZONE.TEE || zones[i] === ZONE.FAIRWAY) divotCells.push(i);
    else if (zones[i] === ZONE.GREEN) markCells.push(i);
  }

  const rounds = state.club?.lastRounds || 0;
  const rng = rngOf(state);
  const divotEvents = Math.min(24, Math.ceil(rounds * 0.32));
  const markEvents = Math.min(14, Math.ceil(rounds * 0.18));
  for (let n = 0; n < divotEvents && divotCells.length; n += 1) {
    const i = divotCells[rng.int(divotCells.length)];
    t.divots[i] = clamp(t.divots[i] + 1, 0, SURFACE_DAMAGE_CAP);
    t.wear[i] = clamp(t.wear[i] + 1.8, 0, 100);
  }
  for (let n = 0; n < markEvents && markCells.length; n += 1) {
    const i = markCells[rng.int(markCells.length)];
    t.ballMarks[i] = clamp(t.ballMarks[i] + 1, 0, SURFACE_DAMAGE_CAP);
    t.wear[i] = clamp(t.wear[i] + 1.25, 0, 100);
  }
  return { divots: divotEvents, ballMarks: markEvents };
}

export function repairSurfaceDamageAt(state, cellIndex, seconds = 1) {
  ensureSurfaceDamage(state);
  const t = state.turf;
  if (!t || !Number.isInteger(cellIndex) || cellIndex < 0 || cellIndex >= t.divots.length) {
    return { ok: false };
  }
  const rate = Math.max(0, seconds) * 1.4;
  const before = t.divots[cellIndex] + t.ballMarks[cellIndex];
  t.divots[cellIndex] = Math.max(0, t.divots[cellIndex] - rate);
  t.ballMarks[cellIndex] = Math.max(0, t.ballMarks[cellIndex] - rate);
  const repaired = Math.max(0, before - t.divots[cellIndex] - t.ballMarks[cellIndex]);
  if (repaired > 0) t.wear[cellIndex] = Math.max(0, t.wear[cellIndex] - repaired * 5);
  return { ok: true, repaired, remaining: t.divots[cellIndex] + t.ballMarks[cellIndex] };
}

export function sectionDamageSummary(state, section) {
  ensureSurfaceDamage(state);
  let divots = 0;
  let ballMarks = 0;
  for (const i of section.cells) {
    divots += state.turf.divots[i] || 0;
    ballMarks += state.turf.ballMarks[i] || 0;
  }
  return {
    divots: Math.round(divots * 10) / 10,
    ballMarks: Math.round(ballMarks * 10) / 10,
  };
}
