// PHASE 1 (Goal 26) — THE PAPERWORK, GENERATED FROM THE MANIFEST.
//
// 1.8 asks for local filename, source page, original title, creator, licence and
// version, required attribution, conversions performed and date obtained, for
// every file. All of that already lives in Assets/audio/manifest.json because
// build-audio.mjs wrote it there while cutting the files -- so the documents are
// GENERATED rather than maintained. A hand-written credits list drifts from the
// files the moment one is re-cut, and a drifted licence list is the one kind of
// mistake in this phase that is not fixable after shipping.
//
// Two documents, because they answer to two different readers:
//   Assets/audio/CREDITS.md     beside the files, gated by tests/audio-sample-licences
//   THIRD_PARTY_ASSETS.md       at the repo root, the shipping record 1.8 asks for
//
//   node tools/audio/write-credits.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '..', '..');
const manifest = JSON.parse(fs.readFileSync(path.join(REPO, 'Assets', 'audio', 'manifest.json'), 'utf8'));
const samples = manifest.samples || [];

const byCue = new Map();
for (const s of samples) {
  if (!byCue.has(s.cue)) byCue.set(s.cue, []);
  byCue.get(s.cue).push(s);
}

const sourceKey = (s) => `${s.source}|${s.licence}|${s.creator}`;
const bySource = new Map();
for (const s of samples) {
  if (!bySource.has(sourceKey(s))) bySource.set(sourceKey(s), []);
  bySource.get(sourceKey(s)).push(s);
}

const credits = [];
credits.push('# Audio credits');
credits.push('');
credits.push('Every recorded sample shipped with GOLF EMPIRE, with its licence and where it');
credits.push('came from. **Generated by `tools/audio/write-credits.mjs` from');
credits.push('`Assets/audio/manifest.json` — do not hand-edit.** The test suite gates it:');
credits.push('a sample without a licence and a source cannot ship, and a sample in the');
credits.push('manifest that is missing here fails `tests/audio-sample-licences.test.js`.');
credits.push('');
credits.push(`**${samples.length} files across ${byCue.size} cues.** Every one is CC0 or CC-BY;`);
credits.push('anything carrying a NonCommercial or ShareAlike term was refused at download');
credits.push('time by `tools/audio/freesound-fetch.mjs`, which re-checks the licence on each');
credits.push("sound's own page rather than trusting the search filter.");
credits.push('');
credits.push('## By cue');
credits.push('');
credits.push('| cue | variants | files | peak dBFS |');
credits.push('|---|---|---|---|');
for (const [cue, list] of byCue) {
  const peaks = list.map((s) => s.peakDb).filter((p) => p !== null);
  const range = peaks.length
    ? (Math.min(...peaks) === Math.max(...peaks)
      ? `${Math.min(...peaks)}`
      : `${Math.min(...peaks)} … ${Math.max(...peaks)}`)
    : '—';
  credits.push(`| \`${cue}\` | ${list.length} | ${list.map((s) => path.basename(s.file)).join(', ')} | ${range} |`);
}
credits.push('');
credits.push('## By source recording');
credits.push('');
for (const [, list] of bySource) {
  const s = list[0];
  credits.push(`### ${s.title}`);
  credits.push('');
  credits.push(`- **Creator:** ${s.creator}`);
  credits.push(`- **Licence:** ${s.licence}`);
  credits.push(`- **Source:** ${s.source}`);
  credits.push(`- **Obtained:** ${s.obtained}`);
  if (s.attribution) credits.push(`- **Required attribution:** ${s.attribution}`);
  credits.push(`- **Used for:** ${[...new Set(list.map((x) => x.cue))].join(', ')}`);
  credits.push(`- **Files:** ${list.map((x) => path.basename(x.file)).join(', ')}`);
  credits.push('');
}
fs.writeFileSync(path.join(REPO, 'Assets', 'audio', 'CREDITS.md'), `${credits.join('\n')}\n`);

const third = [];
third.push('# Third-party assets');
third.push('');
third.push('Everything in this repository that someone else made, with the licence that');
third.push('lets it ship. **Generated by `tools/audio/write-credits.mjs`** for the audio');
third.push('section; do not hand-edit that section.');
third.push('');
third.push('## Licence policy');
third.push('');
third.push('GOLF EMPIRE ships on Steam, so only licences that are **free for commercial use');
third.push('with no attribution trap and no share-alike obligation** are accepted:');
third.push('**CC0-1.0**, **CC-BY-3.0**, **CC-BY-4.0**. NonCommercial, ShareAlike and');
third.push('Sampling+ terms are refused at download time, not at review time.');
third.push('');
third.push('The shipped game plays **vendored local files only** — there is no runtime call');
third.push('to any remote service. Downloads happen at development time through');
third.push('`tools/audio/freesound-fetch.mjs`.');
third.push('');
third.push('## Audio');
third.push('');
third.push(`${samples.length} files, ${(samples.reduce((a, s) => a + (s.bytes || 0), 0) / 1024).toFixed(0)} kB total.`);
third.push('');
third.push('| file | cue | title | creator | licence | source | obtained | attribution required | conversions |');
third.push('|---|---|---|---|---|---|---|---|---|');
for (const s of samples) {
  third.push([
    `\`${path.basename(s.file)}\``,
    `\`${s.cue}\``,
    s.title.replace(/\|/g, '/'),
    s.creator,
    s.licence,
    s.source,
    s.obtained,
    s.attribution || 'none (CC0)',
    (s.conversions || []).join('; '),
  ].join(' | ').replace(/^/, '| ').replace(/$/, ' |'));
}
third.push('');
third.push('### Where each source came from');
third.push('');
third.push('- **freesound.org** — CC0 only, filtered at search and then **re-verified on each');
third.push("  sound's own page** before download. The file vendored is the highest-quality");
third.push('  public preview transcode; under CC0 a derivative carries no restriction, and');
third.push('  the original page is recorded above so the provenance is checkable.');
third.push('- **kenney.nl** — released CC0 by Kenney. The pack page states CC0 and links');
third.push('  `creativecommons.org/publicdomain/zero/1.0/`.');
third.push('');
fs.writeFileSync(path.join(REPO, 'THIRD_PARTY_ASSETS.md'), `${third.join('\n')}\n`);

console.log(`CREDITS.md and THIRD_PARTY_ASSETS.md written for ${samples.length} samples across ${byCue.size} cues.`);
