// Vendors the three renderer libraries into vendor/ as single-file ESM builds.
//
// The app has NO bundler: index.html's import map resolves `three` to
// ./vendor/three.module.js and src/ imports everything by URL. npm install
// alone therefore does nothing for the renderer — these bundles ARE the
// runtime copies, committed to the repo like three.module.js itself.
//
// `three` stays EXTERNAL and BARE in the output: the import map is the single
// authority for where three lives, which guarantees one three instance
// (two copies break instanceof checks across library boundaries).
//
// Rerun after upgrading any of the three packages:
//   node tools/vendor-libs.mjs
import { build } from 'esbuild';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const LIBS = [
  { pkg: 'troika-three-text', out: 'vendor/troika-three-text.module.js' },
  { pkg: 'postprocessing', out: 'vendor/postprocessing.module.js' },
  { pkg: 'three-mesh-bvh', out: 'vendor/three-mesh-bvh.module.js' },
  // C1 (Goal 24) — recast-navigation. The only candidate that GENERATES a
  // navmesh from the scene's own geometry rather than asking for a hand-authored
  // graph, and it carries Detour crowd avoidance. Its WASM is inlined as base64
  // by the package's wasm-compat entry, so there is no second file to fetch and
  // no path for the file:// origin to get wrong; the CSP's 'wasm-unsafe-eval'
  // (committed as decision 1) is what lets it compile.
  //
];

// C1 (Goal 24) — RECAST IS ONE BUNDLE, AND IT HAS TO BE.
//
// The first attempt vendored `core` and `generators` as two files, the way the
// three libraries above are done. They loaded, `init()` resolved in 35 ms under
// the new CSP, and the first call into a generator threw
//
//   "init" must be called before using any recast-navigation-js APIs
//
// because esbuild had inlined a SECOND copy of core into the generators bundle.
// `init()` initialised the copy in one file; the generators held another that
// nobody had touched. This is the identical hazard the header records for
// `three` ("two copies break instanceof checks across library boundaries") in
// its more obvious form — here it is not instanceof that breaks but a module's
// private WASM handle, and the error names the wrong cause.
//
// So both packages are re-exported through ONE entry, which makes one copy the
// only possible outcome rather than something to remember.
const RECAST_OUT = 'vendor/recast-navigation.module.js';
const recastVersion = JSON.parse(
  readFileSync(resolve(root, 'node_modules/@recast-navigation/core/package.json'), 'utf8'),
).version;
await build({
  stdin: {
    contents: "export * from '@recast-navigation/core';\nexport * from '@recast-navigation/generators';\n",
    resolveDir: root,
    sourcefile: 'recast-navigation-entry.js',
    loader: 'js',
  },
  outfile: resolve(root, RECAST_OUT),
  bundle: true,
  format: 'esm',
  platform: 'browser',
  external: ['three'],
  minify: false,
  banner: {
    js: `// GENERATED by tools/vendor-libs.mjs from @recast-navigation/core+generators@${recastVersion} — do not edit by hand.\n`
      + '// ONE bundle on purpose: two would each carry their own copy of core and\n'
      + '// only one of them would ever be init()ed. See the note in the tool.',
  },
  logLevel: 'error',
});
console.log(`${RECAST_OUT} <- @recast-navigation/core+generators@${recastVersion}`);

for (const { pkg, out } of LIBS) {
  const version = JSON.parse(
    readFileSync(resolve(root, 'node_modules', pkg, 'package.json'), 'utf8'),
  ).version;
  await build({
    entryPoints: [pkg],
    outfile: resolve(root, out),
    bundle: true,
    format: 'esm',
    platform: 'browser',
    external: ['three'],
    minify: false,
    banner: {
      js: `// GENERATED by tools/vendor-libs.mjs from ${pkg}@${version} — do not edit by hand.`,
    },
    logLevel: 'error',
  });
  console.log(`${out} <- ${pkg}@${version}`);
}
