// Vendors the three renderer libraries into vendor/ as single-file ESM builds.
//
// The app has NO bundler: index.html's import map resolves `three` to
// ./vendor/three.module.js and src/ imports everything by URL. npm install
// alone therefore does nothing for the renderer — these bundles ARE the
// runtime copies, committed to the repo like three.module.js itself.
//
// `three` stays EXTERNAL and BARE in the output: the import map is the single
// authority for where three lives, which guarantees one three instance
// (two copies break instanceof checks across library boundaries).
//
// Rerun after upgrading any of the three packages:
//   node tools/vendor-libs.mjs
import { build } from 'esbuild';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const LIBS = [
  { pkg: 'troika-three-text', out: 'vendor/troika-three-text.module.js' },
  { pkg: 'postprocessing', out: 'vendor/postprocessing.module.js' },
  { pkg: 'three-mesh-bvh', out: 'vendor/three-mesh-bvh.module.js' },
];

for (const { pkg, out } of LIBS) {
  const version = JSON.parse(
    readFileSync(resolve(root, 'node_modules', pkg, 'package.json'), 'utf8'),
  ).version;
  await build({
    entryPoints: [pkg],
    outfile: resolve(root, out),
    bundle: true,
    format: 'esm',
    platform: 'browser',
    external: ['three'],
    minify: false,
    banner: {
      js: `// GENERATED by tools/vendor-libs.mjs from ${pkg}@${version} — do not edit by hand.`,
    },
    logLevel: 'error',
  });
  console.log(`${out} <- ${pkg}@${version}`);
}
